swagger: "2.0"
info:
  title: BeepBeep Mail Service
  description: Manage email preferences
  license:
    name: AGPL-3.0
    url: https://www.gnu.org/licenses/agpl-3.0.en.html
  version: 0.2.0
basePath: /api
paths:
    /frequency/{user_id}:
      get:
        operationId: getFrequency
        description: Get the frequency preference for mail
        produces:
          - application/json
        parameters:
          - name: user_id
            in: path
            description: ID of user
            required: true
            type: integer
        responses:
          '200':
            description: The current value of the frequency in hour (float)
          '404':
            description: user_id not found, there is not frequency set
      post:
        operationId: setFrequency
        description: Set or update the frequency for the email
        produces:
          - application/json
        parameters:
          - name: user_id
            in: path
            description: ID of user
            required: true
            type: integer
          - name: frequency
            in: query
            description: The chosen frequency in hour of the mail report
            required: true
            type: number
        responses:
          '200':
            description: Ok
          '400':
            description: Bad request, frequency missing
    /reports:
      delete:
        operationId: deleteFrequency
        description: Deletion of all reports of user id
        produces:
          - application/json
        parameters:
          - name: user_id
            in: query
            description: ID of user
            required: true
            type: integer
        responses:
          '200':
            description: Delete all reports
          '400':
            description: Bad request
          '404':
            description: The user does not exists
